### ISSUE TITLE
Move all the source code of the repository to `src` folder

### ISSUE THREAD

**Issue by Dhravya** [cake-cutter/cakecutter#12]
The repository is very cluttered.

**Comment by amoghrajesh** [comment]
@Dhravya is this issue still open? I can take it up.

**Comment by Dhravya** [comment]
The thing with this is... the way packages are set up i suspect something might break. It won't be just a copy+paste it will also need some other changes

I trust @yxshv with this because he has set up the packages

**Comment by Oppodelldog** [comment]
When starting with go for me it was for a longer time unclear how to setup a project, there are some things you need to know about special folders that have a function for go.
[Here's one doc](https://github.com/golang-standards/project-layout) that might give some insights - It is mentioning[ not to use a "src" folder](https://github.com/golang-standards/project-layout#src).


Technically it is possible to use that folder, but cannot remember finding one when looking through go open source projects.

**Comment by Dhravya** [comment]
@Oppodelldog oo, thanks for mentioning that! this was actually a suggestion from someone, and while I do know that moving everything will mess it up, I didn't know the docs recommend against it. I'll close this issue now
